### ISSUE TITLE
Support for uc-gui resource pack

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#122]
### Describe the feature and how it would be used

Hello! 👋 

I released v1.0.0 of my GUI resource pack for UltraCosmetics (https://github.com/dennishzg/uc-gui). It would be great if UC had built-in support for it so that the user only has to add the server resource pack and that's it.

Can you add alternative menus which use the GUI textures of my resource pack? For the main menu and for the buy menu(s) when you buy keys or cosmetics etc. You can find a small tutorial on how to create such a menu in the [README.md](https://github.com/dennishzg/uc-gui#%EF%B8%8F-how-to-use).

The main menu can be opened with `"/uc gui" or "/uc gui main"` and the buykey menu with `"/uc gui buykey"`.

The buttons should work exactly like the items in the default menus. And they also have the same names and descriptions (Unlocked: ...).

If a category in the main menu is disabled it should look like this:

![Screenshot (35)](https://github.com/datatags/UltraCosmetics/assets/33426785/0c87f435-9643-47c7-9fe5-b784d5475979)

### Are there alternatives?

/

**Comment by datatags** [comment]
That looks really nice, I love it!

I'm wondering if it would be better to have a sort of companion plugin for it, which could auto-load the texture pack rather than needing to configure it in `server.properties` (I'm pretty sure that's something plugins can do?) This way, the companion plugin could load its own menus into UC, which guarantees that the current version of the main menu matches the version of the resource pack loaded at any given time. Plus, you could use it for bStats metrics, if you like seeing that sort of thing.

I'd be willing to write the plugin for this if it's something you're interested in, or if you have another idea that's good too.

Thanks again, I can't wait to see this up and running! 😁

**Comment by dennishzg** [comment]
That sounds even better. I didn't know that plugins can do that. Good idea! It would be great if you could write that plugin, thanks! I have no idea how to develop a plugin and I don't want to maintain it 😄.

**Comment by BySwiizen** [comment]
Congratulations for your work @dennishzg, I am totally for support!

To come back to @datatags's message, I think it would be more optimized to have a plugin to automate this via an external plugin or see in [UltraCosmetics](https://github.com/datatags/UltraCosmetics) directly if possible.

**Comment by datatags** [comment]
I'm finally getting it going: https://github.com/datatags/UltraCosmetics-gui-addon

**Comment by datatags** [comment]
I think it's done, so I've published a [release](https://github.com/datatags/UltraCosmetics-gui-addon/releases/tag/v1.0) so you can try it out! You'll need the [very latest build](https://github.com/datatags/UltraCosmetics/actions/runs/5843233780) from Actions in order to run it

**Comment by dennishzg** [comment]
Just tried it out. It was the first time i saw it in action. Everything is working (except the disabled categories stuff). This is so awesome, good job! 👍👍 I love it! 😄

**Comment by datatags** [comment]
Disabled category handling should be fixed in [v1.0.1](https://github.com/datatags/UltraCosmetics-gui-addon/releases/tag/v1.0.1), but you'll again need to download the [very latest build](https://github.com/datatags/UltraCosmetics/actions/runs/5858684110) of UC in order to try it out. If there's nothing else you see that needs improvement, feel free to close this issue 😁

**Comment by dennishzg** [comment]
Disabled categories are fixed. 👍
