### ISSUE TITLE
Cosmetics of a player should only affect players who can see that player

### ISSUE THREAD

**Issue by jandie1505** [datatags/UltraCosmetics#123]
### Describe the feature and how it would be used

If a player has cosmetics enabled, but the player is vanished or hidden by another player, the players who normaly can't see this player can see the cosmetics of that player.

In case of vanishing, this would be ok, because when the player enables vanish, that player can also disable the cosmetics.

In case of a player hider, it causes a problem. This is because the player who is hiding the other players is not the player who can disable the cosmetics of the other players (and also shouldn't be able to do this). This means, that the player is forced to see the cosmetics of other players.

But seeing other cosmetics is not the only problem.
There are some gadgets that can affect other players (e.g. Thor's Hammer can move other players).
It can get extremely annoying and gamebreaking if a player can get moved by other players and can't do anything about it, even if the other players are hidden.

The solution for this problem would be that only players who see the other player can also see their cosmetics (or be affected by their gadgets).

Bukkit provides the method `Player#canSee(Player otherPlayer)` for that, which is used by most of the vanishing plugins and player hiders.

### Are there alternatives?

The only possible alternative for this problem would be to disable cosmetics for all players if any player is hidden, which is also annoying for all players who want to use cosmetics.

**Comment by datatags** [comment]
There is already a config option `Prevent-Cosmetics-In-Vanish` which should automatically disable cosmetics for players with the `vanished` metadata set after a short delay, and vanished players are never affected by other players' cosmetics, regardless of that config setting. So, vanished players should be covered here, even without needing to remember to manually disable cosmetics.

I hadn't considered plugins that might hide players to specific other players, but I think at least particles and gadgets could be supported by this. I can't think of a way to tackle this for mounts that really makes sense, and how morphs are handled for vanished players is up to LibsDisguises, but since everything else is either particles, gadgets, or armor, that should be doable.

**Comment by datatags** [comment]
Should be fixed by e350d2c0960a0ddf6064b8303a3d33e162a5a924
