### ISSUE TITLE
Support for MySQL 8.* version

### ISSUE THREAD

**Issue by Dariusztmt** [datatags/UltraCosmetics#152]
### Describe the feature and how it would be used

Add support for MySQL 8.* version when using database data storage setting. Whenever I try to connect the database with the latest version of the plugin I receive an error for the unknown system variable 'tx_isolation', as it was changed to 'transaction_isolation' in the recent version of MySQL Server.

ERROR:
[12:13:36 WARN]: be.isach.ultracosmetics.shaded.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'tx_isolation'

### Are there alternatives?

Using an older version of MySQL Server, however this kind of practice is not the best choice.

**Comment by datatags** [comment]
I believe it's due to the outdated MySQL driver included in some old versions of spigot/paper/etc (1.12 and under maybe?) Up-to-date server versions work fine. I've looked into this before and I think UC would have to shade an entire updated MySQL driver to fix it, when it's for a bit of a niche situation.

However, current versions of MariaDB don't cause this issue even with the old driver, and since it's just a drop-in replacement for MySQL server (often being recommended MySQL server in general,) that's what I recommend.

This probably won't be resolved in UC unless there's a better way to fix it that I'm not aware of
