### ISSUE TITLE
Rocket gadget should fly higher

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#19]
### Describe the feature and how it would be used

The rocket gadget should fly much higher, at least above the clouds. It's a rocket! 🚀
Layer 220 or 230 is a good height in my opinion.
(There is only a ~25 blocks height difference between the trampoline and the rocket gadget 😄)

### Are there alternatives?

No

**Comment by datatags** [comment]
I believe the rocket currently carries you a certain height above wherever you started, so if you start higher you end higher. So the optimal solution would be to increase the speed or flight time?

**Comment by dennishzg** [comment]
I see. Yes, that should work. I think it should be a combination of a bit more speed and a longer flight time.

**Comment by Chris6ix** [comment]
I agree with Dennis, but I think that it would be great if the gadget could be cancelled by for example pressing the sneak button, so that the player is not forced to always fly that high (That the player can fly as high as they want with the Rocket)
The max height the Rocket can achieve should then also be a config option imo (In Blocks)

Another suggestion would be to lower the countdown of the Rocket from 5 to 3 seconds so that you don't have to wait as long before it starts

**Comment by datatags** [comment]
I've adjusted the rocket so it flies a little faster and just keeps going either until the rocket gets close to the ceiling/build height or until the user dismounts.
