### ISSUE TITLE
Frost Walker enchantment for GlacialSteed mount

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#20]
### Describe the feature and how it would be used

The Glacial Steed mount can walk on water. The water blocks should transform into frosted ice blocks (exactly like the [Frost Walker enchantment](https://minecraft.fandom.com/wiki/Frost_Walker)).

### Are there alternatives?

no

**Comment by datatags** [comment]
I'm not sure about having horses walk on lava. The problem with it is that if UC uses fake blocks like it does for the normal mount trails, the player will get kicked for flying when walking on fake blocks. If UC uses real blocks, it would have to be very careful to make sure:

- Blocks never get left behind
- Blocks cannot be mined
- Blocks cannot be moved with pistons
- Blocks cannot be blown up and harvested
- etc.

Having horses walk on ice would be easy though, because Frost Walker does work when given to horses.

**Comment by dennishzg** [comment]
Is the Frost Walker enchantment which you added in 06d722efea54a32f441ccf76ca05fbc3acb705fd working? If it works, you can close this issue.
I don't think we need a config option where you can disable the Frost Walker enchantment.

**Comment by datatags** [comment]
Sorry, seems I forgot to reply to this. Yes, the frost walker enchantment does work, so I'll go ahead and close this 🙂
